name: my_app3
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.3.2+1
  cupertino_icons: ^0.1.3
  firebase_core: ^0.5.0
  cloud_firestore: ^0.14.0+2
  chopper: ^3.0.3
  chopper_generator: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0

flutter:
  uses-material-design: true
